#!/bin/bash

echo "------ HOOK START - POST-PUSH -------"
#docker tag $IMAGE_NAME $DOCKER_REPO:latest
#docker push $DOCKER_REPO:latest
docker tag $IMAGE_NAME $DOCKER_REPO:1.0.0
docker push $DOCKER_REPO:1.0.0
echo "------ HOOK END - POST-PUSH -------"

